import { Colors, Radius, Spacing, Typography } from '@/constants/theme';
import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';

// 1️⃣ Describe every tab ONCE. The whole UI is generated from this array,
//    so adding a 4th tab later is just one more object here.
const TABS = [
    {
        key: 'posts',
        icon: 'grid-outline',
        iconActive: 'grid',
        emptyIcon: 'images-outline',
        emptyTitle: 'Share your first post',
        emptySubtitle: 'Post a product photo and start selling to your followers.',
        emptyCta: 'Create a post',
    },
    {
        key: 'products',
        icon: 'pricetags-outline',
        iconActive: 'pricetags',
        emptyIcon: 'bag-handle-outline',
        emptyTitle: 'Add your first product',
        emptySubtitle: 'List a product with a price so people can buy it in-app.',
        emptyCta: 'Add a product',
    },
    {
        key: 'orders',
        icon: 'receipt-outline',
        iconActive: 'receipt',
        emptyIcon: 'cube-outline',
        emptyTitle: 'No orders yet',
        emptySubtitle: 'Orders from customers who buy your products show up here.',
        emptyCta: 'Share your shop',
    },
] as const;

const ProfileTabs = () => {
    // 2️⃣ Remember which tab is selected. Seed from the array so state can never
    //    hold a key that doesn't exist (that was the earlier blank-content bug).
    const [activeKey, setActiveKey] = useState<string>(TABS[0].key);

    // 3️⃣ Look up the config for the active tab (drives the content area below).
    const activeTab = TABS.find((tab) => tab.key === activeKey) ?? TABS[0];

    return (
        <View style={styles.container}>
            {/* THE TAB BAR — generated by mapping over TABS */}
            <View style={styles.tabBar}>
                {TABS.map((tab) => {
                    const isActive = tab.key === activeKey;
                    return (
                        <TouchableOpacity
                            key={tab.key}
                            style={[styles.tabButton, isActive && styles.tabButtonActive]}
                            onPress={() => setActiveKey(tab.key)}
                            activeOpacity={0.7}
                        >
                            <Ionicons
                                name={isActive ? tab.iconActive : tab.icon}
                                size={24}
                                color={isActive ? Colors.text : Colors.textSecondary}
                            />
                        </TouchableOpacity>
                    );
                })}
            </View>

            {/* THE CONTENT — the active tab's empty state for now.
          Later this becomes a FlatList of real products. */}
            <View style={styles.content}>
                <View style={styles.emptyIconCircle}>
                    <Ionicons name={activeTab.emptyIcon} size={30} color={Colors.textSecondary} />
                </View>
                <Text style={styles.emptyTitle}>{activeTab.emptyTitle}</Text>
                <Text style={styles.emptySubtitle}>{activeTab.emptySubtitle}</Text>
                <TouchableOpacity style={styles.ctaButton} activeOpacity={0.85}>
                    <Text style={styles.ctaText}>{activeTab.emptyCta}</Text>
                </TouchableOpacity>
            </View>
        </View>
    );
};

const styles = StyleSheet.create({
    container: { flex: 1 },
    tabBar: {
        flexDirection: 'row',
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: Colors.border,
    },
    tabButton: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: Spacing.md,
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    tabButtonActive: {
        borderBottomColor: Colors.text,
    },
    content: {
        flex: 1,
        alignItems: 'center',
        paddingTop: Spacing.xxl + Spacing.lg,
        paddingHorizontal: Spacing.xl,
    },
    emptyIconCircle: {
        width: 72,
        height: 72,
        borderRadius: Radius.full,
        backgroundColor: Colors.surfaceMuted,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: Spacing.lg,
    },
    emptyTitle: {
        ...Typography.headlineMd,
        color: Colors.text,
        textAlign: 'center',
        marginBottom: Spacing.sm,
    },
    emptySubtitle: {
        ...Typography.bodySm,
        color: Colors.textSecondary,
        textAlign: 'center',
        marginBottom: Spacing.xl,
    },
    ctaButton: {
        backgroundColor: Colors.primary,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.xxl,
        borderRadius: Radius.full,
        alignItems: 'center',
    },
    ctaText: {
        ...Typography.labelBold,
        color: Colors.onPrimary,
        fontSize: 15,
    },
});

export default ProfileTabs;
